### ISSUE TITLE
Correct vendor and distribution names in `installer.py`

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/photon-os-installer#10]
Ideally, the name of this repo should be more like `repo_file.write("name=VMware Photon OS Installer\n") ` to conform with the correct spelling of the vendor (VM**w**are) and the correct distribution name (Photon **OS**).

https://github.com/vmware/photon-os-installer/blob/871dc56f205b68488dc85ca7613356225c87239d/photon_installer/installer.py#L864

**Comment by tenthirtyam** [comment]
@gpiyush-dev - Could you review the issue and linked pull request?

Ryan

**Comment by gpiyush-dev** [comment]
Reviewed and merged the changes through internal review.
