### ISSUE TITLE
ensure that postinstall scripts are executeable

### ISSUE THREAD

**Issue by terefang** [vmware/photon-os-installer#12]
### Describe the bug

ensure that postinstall scripts that are packaged by kickstarter to be executable

add the chmod line in the section in m_postinstall.py:

```
    for script in os.listdir(tempdir_full):
        installer.logger.info("Running script {}".format(script))
        os.chmod(os.path.join(tempdir_full, script), 0o700)
        installer.cmd.run_in_chroot(installer.photon_root, "{}/{}".format(tempdir, script))
```

### Reproduction steps

```bash
packaging post installation scripts without executable flag set
```

### Expected behavior

ensure that postinstall scripts to be executable

**Comment by gpiyush-dev** [comment]
Resolved with https://github.com/vmware/photon-os-installer/commit/b878ef28966274e52b9b2ef538190656ce7782a8
