### ISSUE TITLE
photon-os-installer boot on usb-c hub environments

### ISSUE THREAD

**Issue by dcasota** [vmware/photon-os-installer#14]
### Is your feature request related to a problem? Please describe.

Hi @gpiyush-dev,
The latest release with multiple partitions support is great. * congrats !

In https://github.com/vmware/photon/issues/1300#issuecomment-1319864452, see the Photon OS aarch64 on RPI4 scenario with usb-c hub attached mmc sdcards. Actually, photon-os-installer boots from the usb-c adapter plugged-in mmc sdcard, but doesn't do anything with that one or any additional mmc sdcard as they are not recognized during Photon OS aarch64 minimal setup boot.

### Describe the solution you'd like

Detect usb-c hub attached medias (mmc, usb)

### Describe alternatives you've considered

Provisioning Photon OS on RPI4 works with directly attached usb media.

**Comment by dcasota** [comment]
Here a photon-os-installer update using the 5.0 early beta iso bits, on baremetal x86_64 laptop, in addition to J)K) in https://github.com/vmware/photon/issues/1385.

I've tried two tecniques: 1) Ventoy configured media with Photon OS 5.0 early beta iso bits on it. 2) Rufus provisioned media of Photon OS 5.0 early iso bits

1) With a Rufus provisioned media, booting from mmc sd card / usb media stops after the initial Photon OS screen with "error: bad shim signature". Same result without/with usb-c hub environment.

2) With a Ventoy configured media, Photon-os-installer successfully boots from the usb-c adapter plugged-in media (mmc sdcard or usb media) and installs Photon OS on another plugged-in mmc sd card / usb media. But then, booting from that mmc sd card / usb media stops after the initial Photon OS screen with "error: bad shim signature".

**Comment by dcasota** [comment]
Here a finding.

On a baremetal x86_64 laptop with **secure boot enabled**, a Ventoy usb media boots a slipstreamed photon-4.0-5347f73fc.iso in Ventoy' grub2 mode. The Photon-os-installer starts from the usb-c adapter plugged-in media (usb). It installs Photon OS on another plugged-in mmc sd card. 
The installation remains quite while on partitioning. During this phase I've switched the screen (alt-F2) and displayed dmesg output. There is a flood of messages "usb2-port4: Cannot enable. Maybe the USB cable is bad?"

![usb2-port4](https://user-images.githubusercontent.com/14890243/223276681-b35f84ad-002a-4d69-a1b7-d81e42c71957.png)

Nevertheless, the partitioning succeeds and the installation successfully finishes.
Now, this works with 1x usb media and 1 mmc card on the plugged-in usb-2 adapter hub.
With a 2nd mmc card, the partitioning takes longer and the installation often fails. Tested with different mmc cards.
This "usb2-port4" messages aren't good.

As expected for now, booting from the prepared mmc media stops after the initial Photon OS screen with "error: bad shim signature".

**Comment by YustasSwamp** [comment]
Hi @dcasota ,
The USB cable error message can be result of bad cable), usb hub or usb port.
To get more kernel debug messages you can try booting with cmdline parameter `dyndbg="file drivers/usb/core/hub.c +p"`

I didn't get the signature issue details and why it is expected.

BTW, there 2 additional options how you can install Photon OS on mmc card. In both cases you can run photon installer without booting installer ISO. You can use Photon box or even photon docker image for the next 2 options:
1. run photon installer directly as a python app and to specify external mmc card as a target disk.
2. run photon installer directly as a python app and use loopback attached raw file. Later this file can be flashed to mmc card.

**Comment by dcasota** [comment]
Hi @YustasSwamp,

Thank you for the suggestions.

usb-c scenarios with secure boot + usb media, mmc, [fill-in], still is developer space.
Unfortunately, I'm not skilled enough for kernel debug tasks.

To use the Ventoy boot tool as previously assumed alternative for the missing shim signature enhancement does not fit. This is the message for the moment.

In addition, Ventoys' grub2 mode - which uses his own shim signature - is based on grub2.04 and cmdline parameter dyndbg isn't supported.

Here's the GUI trace:

1. Ventoy with the photon-4.0-5347f73fc.iso boots on the selectephoton-4.0-5347f73fc.iso boots on the selected usb hard d usb hard drive (uefi) media.  
![ph4_ventoy1](https://user-images.githubusercontent.com/14890243/223370738-369b4909-a650-4625-8402-34603911bb11.png)

2. Ventoy boot screen lists all isos on the media. Select photon-4.0-5347f73fc.iso .  
![ph4_ventoy2](https://user-images.githubusercontent.com/14890243/223372166-b54baa6a-6024-48ab-b402-dae8fd152029.png)

3.  Select grub2 mode  
    ![ph4_ventoy3](https://user-images.githubusercontent.com/14890243/223373139-88565c0c-d966-4362-8e7e-94cbb1baeaa3.png)

4. In grub2 mode, add cmdline parameter dyndbg="file drivers/usb/core/hub.c +p"  
![ph4_ventoy4](https://user-images.githubusercontent.com/14890243/223376981-e21df41d-d1c4-4ddf-bff8-03567ecafb2e.png)

5. The cmdline parameter isn't supported.  `systemd.debug-shell=1` isn't recognized in Ventoys' grub2 mode as well.
![ph4_ventoy5](https://user-images.githubusercontent.com/14890243/223378262-6db487f6-fdac-49a2-a9dc-ec5c596890fc.png)

As described, in grub2 mode (without cmdline parameter dyndbg), the photon-4.0-5347f73fc.iso successfully installs e.g. on a mmc card.
The usb-c adapter hub is a relatively new ISY adapter IAD-1025 USB-C 6-in-1 hub. The only finding was the time amount during partitioning and the dmesg entries "usb2-port4: Cannot enable. Maybe the USB cable is bad?".

Of course, when secure boot with Ventoy normal mode or without Ventoy, it uses Photon OS installer grub' version, but as any shim signature is missing, it fails to boot. Hence, the parameter dyndbg doesn't help.

The "expectation" refers to https://communities.vmware.com/t5/Photon-OS-Discussions/How-to-install-and-configure-Wi-Fi-drivers-in-Photon-OS/m-p/2934678/highlight/true#M342 and means no time frame. 

No doubt, the 2 additional options will help in a future Secure Boot constellation.

I hope the pictures and description help.
-Daniel

**Comment by dcasota** [comment]
fyi re-tested the issue constellation with latest slipstreamed Ph5.0 bits, but no progress yet.

1.  student lab
    1x ISY adapter IAD-1025 USB-C 6-in-1 hub
    1x Usb media kingston traveler 64GB
    1x Raspberry Pi 4B (8GB Ram) with 32GB sdcard
![IMG_1692](https://user-images.githubusercontent.com/14890243/234858915-d92addf8-53eb-4d54-8147-678fca4269b2.jpg)

3.  RPi4 boot from usb media (kingston traveler), provisioned with photon-minimal-5.0-dde71ec57.aarch64.iso
![IMG_1689](https://user-images.githubusercontent.com/14890243/234856904-086992c1-1304-4380-a674-7fde33967ed7.jpg)

4.  Photon-os-installer starts but fails because it does NOT detect the usb media (kingston traveler, see above), plugged-in on a usb-c hub. The RPi4 (firmware) sdcard is detected only.
![IMG_1690](https://user-images.githubusercontent.com/14890243/234857366-c423cf5d-b62e-49e7-900a-d61ec7eda684.jpg)

**Comment by dcasota** [comment]
usb-c hub attached medias (mmc, usb) remained unsupported
