### ISSUE TITLE
arm64 support for hyperscalers

### ISSUE THREAD

**Issue by dcasota** [vmware/photon-os-installer#22]
### Is your feature request related to a problem? Please describe.

Hi Photon OS Installer team,

The first hyperscalers introduced arm64 support a few months ago.

Could Photon-OS-installer support additional combinations e.g. azure-aarch64 + ami-aarch64 for Photon OS Next-Generation as well ?

### Describe the solution you'd like

<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(240, 243, 246); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(10, 12, 16); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">More images that can be build based on architecture mentioned in table.</p>

x86_64 | arm64
-- | --
iso | iso
ova | ova
ova_uefi | ova_uefi
minimal-iso |  minimal-iso
rt-iso |  rt-iso
ami |  ami
gce |  gce
azure |  azure
 (n/a) |  rpi3

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(240, 243, 246); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(10, 12, 16); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p>
</body>
</html>

**Comment by dcasota** [comment]
no answer -> close

**Comment by oliverkurth** [comment]
We do support `arm64` (in the `poi-container` branch), see https://github.com/vmware/photon-os-installer/tree/poi-container/docker . You can even build for arm64 on x86 platforms, using the `--platform=linux/arm64` option for docker.

**Comment by dcasota** [comment]
Thanks! This is great stuff! Please, let add more early Photon OS docs chapters. People read Photon OS docs for sure!!
