### ISSUE TITLE
create-image-util with docker-buildx

### ISSUE THREAD

**Issue by dcasota** [vmware/photon-os-installer#26]
### Is your feature request related to a problem? Please describe.

Please consider docker-buildx instead of docker only. create-image-utils fails with on x86_64 Photon OS 5.0 with docker 24.05 because of an known issue "unknown flag: --build-context".

### Describe the solution you'd like

- user gets an information when running ./create-image-util that `docker-buildx` is required.
- e.g. `tdnf install docker-buildx` or separate download to `/usr/bin` from https://github.com/docker/buildx/releases.
- `./create-image-util` uses in line 55 and 57  `sudo docker-buildx build --build-context  ...`

**Comment by oliverkurth** [comment]
Thanks for the report. I think this should be fixed in the Photon `docker` packages though. Photon should have a `docker` sub package that provides the `docker` `buildx` plugin.

Can you file an issue at https://github.com/vmware/photon ?

I noticed this myself a while ago, but forgot.

**Comment by oliverkurth** [comment]
This is how I fixed it: download the plugin from https://github.com/docker/buildx and move to /usr/lib/docker/cli-plugins/docker-buildx. Also do chmod ugo+x on it.
